# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: aws-python # NOTE: update this with your service name

provider:
  name: aws
  runtime: python3.7

functions:
  hello:
    handler: handler.dilbert
    events:
      - schedule:
          rate: cron(0 6 ? * MON-FRI *)
          enabled: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    usePipenv: true
    dockerizePip: true
